version: 2.0
jobs:
  add-consul:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker-k8:1.8
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: ./consul-k8s-go.sh "sandbox.twdps.io"
      - run:
          command: ./test-consul.sh
  delete-consul:
    docker:
      - image: quay.io/thoughtworks_aelab/circleci-docker-k8:1.8
        auth:
          username: $DOCKER_USER
          password: $QUAY_TOKEN
    steps:
      - checkout
      - run:
          command: ./cleanup "sandbox.twdps.io"

workflows:
  version: 2
  consul:
    jobs:
      - add-consul
      - approve-delete-consul:
         type: approval
      - delete-consul:
         requires:
           - approve-delete-consul
